### ISSUE TITLE
 Handling the attributes in xml

### ISSUE THREAD

**Issue by ligilmoneylal** [uacaps/NSObject-ObjectMap#12]
Now there is no manipulation for attributes they are simply ignored. Adding this will completely avoid the effort of xml parsing.
It should be better to map the attributes inside a tag to the same named properties within the object as in case of elements do
for eg : Need to handle the tag 
![screen shot 2014-01-07 at 10 21 24 am](https://f.cloud.github.com/assets/5699156/1865841/69c94540-781c-11e3-967d-0737138d87b6.png)

**Comment by MatthewYork** [comment]
I'm going to close this as it isn't so much a bug as it is a feature. We have never supported such behavior from version 1, but have always gone with element serialization/deserialization, much like what comes out of a Web API method from Microsoft. Web services are the primary target here, not traditional XML document parsing.We aren't trying to parse true XML so much as do object serialization and deserializations coming from the service. While working with attributes instead of child elements would certainly be more efficient, it isn't something we see done in the services we typically use, so we don't handle this case.
