### ISSUE TITLE
Suddenly stopped working for a simple nested object

### ISSUE THREAD

**Issue by rahulvyas** [uacaps/NSObject-ObjectMap#25]
Hi,

I am using this library for the last 4 years. Now suddenly it's not working for a simple object. I'm using an Apple M1 mac could this be an issue?  I have response like this 

```
"dateTime": "26-Apr-2022 9:00:06 AM",
            "postType": "FRIEND",
            "postCreationTimestamp": 1650963267,
            "linkPreview": null,
            "videoStreaming": {
                "channelName": "CDC6423B-331C-4E21-AA21-A45C8D36CFA8"
            },
```

And this is my Data Model properties. I have not added all properties here.

@property (nonatomic,strong) NSNumber* postCreationTimestamp;
//Added For Live Video Streaming
@property (nonatomic,strong) DNLiveStreamingChannel* videoStreaming;

The issue I'm getting is videoStreaming is always getting nil even if it's available in response. However other objects are getting parsed properly. How do I fix this issue?

UPDATE - When I debugged it I found that it's type is always NSNULL instead of class Type

**Comment by rgwebb** [comment]
Greetings Rahul, 

I am the project manager for the team that originally wrote this library. Do you know if this still works in Xcode when using Intel-based Macs? 

For whatever it is worth, our team has not begun a proper transition to Apple Silicon. If the issue is due to platform changes it may be hard to resolve this issue until we get the hardware and opportunity to review legacy code.

**Comment by rahulvyas** [comment]
Hi,

Thanks for your reply, My issue is resolved. I doubt on group folder name which we create in Xcode. I deleted the group folder and put the class outside and it worked. I am still not sure how this is fixed but it's working at the moment. We can close the issue now. If I face the issue again I'll reopen the issue.
